Es features done
sivtsova/andersen-js-course pull request #1
Opened 2019-06-04 19:42 UTC by sivtsova

2019-06-08 09:57 UTC, volvachev requested changes

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task1.js
> +    return !!(!callback && array.some(x=> !!x) || callback && array.some(callback));
Усложнила, воспользуйся параметром по умолчанию для функции.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task2.js
> +        for (let i = 0; i < array1.length; i++) {
Воспользуйся встроенными методами массива.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task4.js
> +    let check = (array1) => {
Воспользуйся новой структурой данных из es6.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task5.js
> +    var a = function () {
почему создаётся функция?
просто обычный объект создавай.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task5.js
> +        if (i < array.length) {
воспользуйся тернарным оператором.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task5.js
> +            if (i < array.length) {
тернарный оператор

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task6.js
> +    array.forEach((item) => {
Есть более подходящий метод массива для такого.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task7.js
> +    for (let i = 0; i < from; i++) {
Усложнила.
Подбери метод массива для такого поведения.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task8.js
> +    array.forEach((item) => {
Усложнила.
Подбери метод массива для такого поведения.

2019-06-08 09:57 UTC, volvachev commented on src/array-practice/task9.js
> +    while ((i = array.indexOf(value, i + 1)) !== -1) {
Воспользуйся методам массива, тут все намного проще.

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task10.js
> +        return super.getName() + ' ' + text;
template string(es6)

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task4.js
> +        x: x,
Сокращенная запись методов и свойств из es6.
так же динамическое свойство
```
{
  [calculate()]: 'test field'
}
```

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task6.js
> +    return [tmp().name, tmp().value, tmp().role.name, tmp().isActive === undefined ? false : tmp().isActive, tmp().cases[0].id];
каждый раз вызывать функцию не хорошо.
Воспользуйся деструктуризацией и должен быть один вызов.

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task7.js
> +    return obj; // obj = {test: 0, foo: 1, bar: 2}
Есть готовый метод для такого поведение в es6

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task8.js
> +            this.nums.forEach((v) => {
Воспользуйся методом массива который подходит под такое поведение.

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task9.js
> +    var result = 'test'.indexOf('est') !== -1;
Воспользуйся методом из es6

2019-06-08 09:57 UTC, volvachev commented on src/es-features/task9.js
> +    var findResult = [22, 1, 90, 70].filter(x => x < 3)[0];
Воспользуйся методом из es6

2019-06-08 16:16 UTC, sivtsova commented on src/array-practice/task1.js
> +    return !!(!callback && array.some(x=> !!x) || callback && array.some(callback));
Исправлено. Сверх усложнила. А казалось наоборот.

2019-06-08 16:51 UTC, sivtsova commented on src/array-practice/task2.js
> +        for (let i = 0; i < array1.length; i++) {
Изменила на reduce.

2019-06-09 13:28 UTC, volvachev requested changes

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task1.js
> +  return !!array.some(callback);
Преобразовывать к булеану не надо через !! . some возвращает уже булеан.

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task10.js
> +  return meetups.reduce((previousValue, item) => {
деструктурируй item.

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task4.js
> +  return arrayResult;
Воспользуйся новой структуруй данной из es6. (Set)

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task5.js
> +  return a;
возвращай сразу объект.
```
let i = 0;
return {
  next() {
     return i < array.length ? array[i++] : 'Complete!';
  }
}
```

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task6.js
> +  array.push(start);
Удали это и разберись со всеми аргументами reduce.

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task2.js
> +    return array1.reduce((res, item) => {
Усложнила воспользуйся filter и includes. Дальше додумай как это всё объединить в одно решение.

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task7.js
> +  array.splice(value);
splice мутирует исходный массив, есть более подходящий метод.

2019-06-09 13:28 UTC, volvachev commented on src/array-practice/task8.js
> +    return values.indexOf(el) < 0;
includes вместо indexof.

2019-06-09 13:28 UTC, volvachev commented on src/es-features/task4.js
> +  obj[`baz${foo()}`] = 'new field';
вынеси это сразу в объект
```
{
 x,
 y,
[`baz${foo()}`]: 'new field'
}
```

2019-06-09 13:28 UTC, volvachev commented on src/es-features/task6.js
> +  var tmp = {
Верни функции, вызови её и сделай деструктуризацию результат
```
const example = () => ....;

const {name, age} = example();
```

2019-06-09 13:28 UTC, volvachev commented on src/es-features/task9.js
> +  var findResult = [22, 1, 90, 70].filter(x => x < 3);
воспользуйся find, и тогда не надо будет делать flat.
в задаче было что брался первый найденный элемент.

2019-06-09 16:50 UTC, volvachev requested changes

2019-06-09 16:50 UTC, volvachev commented on src/array-practice/task4.js
> +  arrayOne.concat(arrayTwo).forEach((item) => {
Разберись как это работает.
```
export function union(arrayOne, arrTwo) {
  return [...new Set([...arrayOne, ...arrTwo])];
}
```

2019-06-09 16:50 UTC, volvachev commented on src/es-features/task6.js
> +  const { name, value, role: { name: roleName }, isActive, cases } = tmp();
При деструктуризации можно указывать значение по умолчанию, если нет в объекте. (это к полю isActive)
так же можно деструктурировать несколько уровней (это к полю cases)

2019-06-09 16:50 UTC, volvachev commented on src/es-features/task9.js
> +  var findResult = [22, 1, 90, 70].filter(x => x < 3)[0];
Воспользуйся методом  из es6. называется find.

2019-06-09 16:50 UTC, volvachev commented on src/array-practice/task2.js
> +  arrayResult = [...arrayResult, ...check(arrayTwo, arrayOne)];
попробуй реализовать так чтобы, filter прошёлся один раз, у тебя сейчас два раза. Сделай один массив и пройдись фильтром плюс includes по каждому массиву.

2019-06-09 17:41 UTC, volvachev requested changes

2019-06-09 17:41 UTC, volvachev commented on src/es-features/task6.js
> +  const { name, value, role: { name: roleName }, isActive = false, cases: { 0: { id } } } = tmp();
Массив надо было так дестркутурировать.

```
const { name, value, role: { name: roleName }, isActive = false, cases: [{ id }] } = tmp();
```

2019-06-09 17:41 UTC, volvachev commented on src/array-practice/task2.js
> +    if (!arrayOne.includes(item) || !arrayTwo.includes(item)) {
```
return [...arrayOne, ...arrTwo].filter(item=> !arrTwo.includes(item) || !arr.includes(item));
```

2019-06-17 18:26 UTC, merged